module.exports = [
  // test_sensors
  {
    id: 'test_offline_01',
    test: true,
    offline: false,
    name: 'test #1',
    loc: '仓库401',
    group: 'sydc1',
    tag_mesa: "measurement=TEST,where_type=TEST",
    kpi: 'controller',
  },
  // sydc2_lt_dock
  {
    id: 'sydc2_lt_dock_01',
    offline: false,
    name: 'D#C T1',
    loc: '二号库-低温码头',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=mt,what3=air,what4=h01,output=temp_c,tool=sample,time_step=5t,at=dock,where1=dl_1_1,where3=4m",
    kpi: 'lt_dock',
  },
  {
    id: 'sydc2_lt_dock_02',
    name: 'D#B T1',
    loc: '二号库-低温码头',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=mt,what3=air,what4=h03,output=temp_c,tool=sample,time_step=5t,at=dock,where1=dl_1_2,where3=4m",
    kpi: 'lt_dock',
  },
  {
    id: 'sydc2_lt_dock_03',
    name: 'D#A T1',
    loc: '二号库-低温码头',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=mt,what3=air,what4=h05,output=temp_c,tool=sample,time_step=5t,at=dock,where1=dl_1_3,where3=4m",
    kpi: 'lt_dock',
  },
  // sydc1_freezer
  {
    id: 'sydc1_freezer_01',
    name: 's10',
    loc: '一号库-冷冻库',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=lt,what3=air,what4=s10,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_1_1,where3=8_5m",
    kpi: 'freezer',
  },
  {
    id: 'sydc1_freezer_02',
    name: 's11',
    loc: '一号库-冷冻库',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=lt,what3=air,what4=s11,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_1_1,where3=2m",
    kpi: 'freezer',
  },
  {
    id: 'sydc1_freezer_03',
    name: 's14',
    loc: '一号库-冷冻库',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=lt,what3=air,what4=s14,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_1_1,where3=2m",
    kpi: 'freezer',
  },
  {
    id: 'sydc1_freezer_04',
    name: 's16',
    loc: '一号库-冷冻库',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=lt,what3=air,what4=s16,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_1_1,where3=8_5m",
    kpi: 'freezer',
  },
  {
    id: 'sydc1_freezer_05',
    name: 's08',
    loc: '一号库-冷冻库',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=lt,what3=air,what4=s08,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_1_1,where3=4m",
    kpi: 'freezer',
  },
  {
    id: 'sydc1_freezer_06',
    name: 's02',
    loc: '一号库-冷冻库',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=lt,what3=air,what4=s02,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_1_1,where3=4m",
    kpi: 'freezer',
  },
  // sydc1_coolroom
  {
    id: 'sydc1_coolroom_01',
    name: 's01',
    loc: '一号库-冷藏库',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=mt,what3=air,what4=s01,output=temp_c,tool=sample,time_step=5t,at=room,where1=rm_1_1",
    kpi: 'coolroom',
  },
  {
    id: 'sydc1_coolroom_02',
    name: 's02',
    loc: '一号库-冷藏库',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=mt,what3=air,what4=s02,output=temp_c,tool=sample,time_step=5t,at=room,where1=rm_1_1",
    kpi: 'coolroom',
  },
  // sydc1_dry_wh1
  {
    id: 'sydc1_dry_wh1_01',
    name: 's14',
    loc: '一号库-干仓#1',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s14,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_1,where2=zone_1_1,where3=10m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh1_02',
    name: 's09',
    loc: '一号库-干仓#1',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s09,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_1,where2=zone_1_1,where3=6m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh1_03',
    name: 's05',
    loc: '一号库-干仓#1',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s05,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_1,where2=zone_1_2,where3=2m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh1_04',
    name: 's07',
    loc: '一号库-干仓#1',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s07,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_1,where2=zone_1_2,where3=2m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh1_05',
    name: 's08',
    loc: '一号库-干仓#1',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s08,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_1,where2=zone_1_2,where3=10m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh1_06',
    name: 's13',
    loc: '一号库-干仓#1',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s13,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_1,where2=zone_1_2,where3=6m",
    kpi: 'dry_wh',
  },
  // sydc1_dry_wh2
  {
    id: 'sydc1_dry_wh2_01',
    name: 's12',
    loc: '一号库-干仓#2',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s12,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_2,where2=zone_2_0,where3=10m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh2_02',
    name: 's03',
    loc: '一号库-干仓#2',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s03,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_2,where2=zone_2_0,where3=2m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh2_03',
    name: 's02',
    loc: '一号库-干仓#2',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s02,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_2,where2=zone_2_0,where3=6m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh2_04',
    name: 's01',
    loc: '一号库-干仓#2',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s01,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_2,where2=zone_2_0,where3=10m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh2_05',
    name: 's11',
    loc: '一号库-干仓#2',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s11,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_2,where2=zone_2_0,where3=6m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_wh2_06',
    name: 's15',
    loc: '一号库-干仓#2',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s15,output=temp_c,tool=sample,time_step=5t,at=room,where1=rd_1_2,where2=zone_2_0,where3=2m",
    kpi: 'dry_wh',
  },
  // sydc1_dry_dock
  {
    id: 'sydc1_dry_dock_01',
    name: 's01',
    loc: '一号库-干仓码头',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s01,output=temp_c,tool=sample,time_step=5t,at=dock,where1=dd_1_1,where3=2m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_dock_02',
    name: 's02',
    loc: '一号库-干仓码头',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what3=air,what4=s02,output=temp_c,tool=sample,time_step=5t,at=dock,where1=dd_1_1,where3=4m",
    kpi: 'dry_wh',
  },
  {
    id: 'sydc1_dry_dock_03',
    name: 'CO',
    loc: '一号库-干仓码头',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=drystore,what2=heating,what3=air,what4=s02,output=co_ppm,tool=sample,time_step=5t,at=dock,where1=dd_1_1,where2=zone_1_0",
    kpi: 'dry_dock_co',
  },
  // sydc1_lt_dock
  {
    id: 'sydc1_lt_dock_01',
    name: 's01',
    loc: '一号库-低温码头',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=lt,what3=air,what4=s01,output=temp_c,tool=sample,time_step=5t,at=dock,where1=dl_1_1",
    kpi: 'lt_dock',
  },
  {
    id: 'sydc1_lt_dock_02',
    name: 's02',
    loc: '一号库-低温码头',
    group: 'sydc1',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang01,what_type=env,what1=frig,what2=lt,what3=air,what4=s02,output=temp_c,tool=sample,time_step=5t,at=dock,where1=dl_1_1",
    kpi: 'lt_dock',
  },
  // sydc2_freezer_A1
  {
    id: 'sydc2_freezer_A1_01',
    name: 'A#1 T1',
    loc: '二号库-冷冻库A-1',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=f02,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_a_1,where3=2m",
    kpi: 'freezer',
  },
  {
    id: 'sydc2_freezer_A1_02',
    name: 'A#1 T2',
    loc: '二号库-冷冻库A-1',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=f03,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_a_1,where3=8_5m",
    kpi: 'freezer',
  },
  {
    id: 'sydc2_freezer_A1_03',
    name: 'A#1 T3',
    loc: '二号库-冷冻库A-1',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=f10,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_a_1,where3=8_5m",
    kpi: 'freezer',
  },
  // sydc2_freezer_A2
  {
    id: 'sydc2_freezer_A2_01',
    name: 'A#2 T1',
    loc: '二号库-冷冻库A-2',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=g02,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_a_2,where3=2m",
    kpi: 'freezer',
  },
  // sydc2_freezer_B1
  {
    id: 'sydc2_freezer_B1_01',
    name: 'B#1 T1',
    loc: '二号库-冷冻库B-1',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=e01,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_b_1,where3=4m",
    kpi: 'freezer',
  },
  {
    id: 'sydc2_freezer_B1_02',
    name: 'B#1 T2',
    loc: '二号库-冷冻库B-1',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=e05,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_b_1,where3=2m",
    kpi: 'freezer',
  },
  {
    id: 'sydc2_freezer_B1_03',
    name: 'B#1 T3',
    loc: '二号库-冷冻库B-1',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=e06,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_b_1,where3=8_5m",
    kpi: 'freezer',
  },
  // sydc2_freezer_B2
  {
    id: 'sydc2_freezer_B2_01',
    name: 'B#2 T1',
    loc: '二号库-冷冻库B-2',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=d02,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_b_2,where3=2m",
    kpi: 'freezer',
  },
  {
    id: 'sydc2_freezer_B2_02',
    name: 'B#2 T2',
    loc: '二号库-冷冻库B-2',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=lt,what3=air,what4=d06,output=temp_c,tool=sample,time_step=5t,at=room,where1=rl_b_2,where3=4m",
    kpi: 'freezer',
  },
  // sydc2_coolroom_C1
  {
    id: 'sydc2_coolroom_C1_01',
    name: 'C#1 T1',
    loc: '二号库-冷藏库C-1',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=mt,what3=air,what4=c01,output=temp_c,tool=sample,time_step=5t,at=room,where1=rm_c_1,where3=4m",
    kpi: 'coolroom',
  },
  {
    id: 'sydc2_coolroom_C1_02',
    name: 'C#1 T2',
    loc: '二号库-冷藏库C-1',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=mt,what3=air,what4=c05,output=temp_c,tool=sample,time_step=5t,at=room,where1=rm_c_1,where3=2m",
    kpi: 'coolroom',
  },
  // sydc2_coolroom_C2
  {
    id: 'sydc2_coolroom_C2_01',
    name: 'C#2 T1',
    loc: '二号库-常温库C-2',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=mt,what3=air,what4=b01,output=temp_c,tool=sample,time_step=5t,at=room,where1=rm_c_2,where3=2m",
    kpi: 'normalroom',
  },
  {
    id: 'sydc2_coolroom_C2_02',
    name: 'C#2 T2',
    loc: '二号库-常温库C-2',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=mt,what3=air,what4=b05,output=temp_c,tool=sample,time_step=5t,at=room,where1=rm_c_2,where3=4m",
    kpi: 'normalroom',
  },
  // sydc2_coolroom_C3
  {
    id: 'sydc2_coolroom_C3_01',
    name: 'C#3 T1',
    loc: '二号库-冷藏库C-3',
    group: 'sydc2',
    tag_mesa: "measurement=li.base.v1.yum.fac,where_type=fac,where=shenyang02,what_type=env,what1=frig,what2=mt,what3=air,what4=a02,output=temp_c,tool=sample,time_step=5t,at=room,where1=rm_c_3,where3=2m",
    kpi: 'coolroom',
  },
];
